# Generated by Django 5.2.3 on 2026-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_comment_created_at_alter_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/posters/', verbose_name='Постер'),
        ),
    ]
