# Generated by Django 5.2.3 on 2026-03-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='movies/posters/', verbose_name='Постер'),
        ),
    ]
